name: Formatter
on: pull_request
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actionsx/prettier@v2
        with:
          args: --write .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: BOT-> Apply Prettier Formatting Changes
